# Generated by Django 6.1 on 2026-08-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0006_medicine_pcs_per_strip_medicine_strips_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blood_pressure_diastolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='blood_pressure_systolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('REGULAR', 'Regular'), ('PREMIUM', 'Premium')], default='BASIC', max_length=10),
        ),
        migrations.CreateModel(
            name='CustomerMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=255)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('permission_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='customers.customer')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_medicines', to='inventory.medicine')),
            ],
            options={
                'ordering': ['customer__name', 'medicine__name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('days_of_week', models.CharField(default='DAILY', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='customers.customermedicine')),
            ],
            options={
                'ordering': ['reminder_time'],
            },
        ),
    ]
