# Generated by Django 6.1 on 2026-08-20 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_membership'),
        ('inventory', '0007_medicinegroup_medicine_cost_price_medicine_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineRefillReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_date', models.DateField(db_index=True)),
                ('refill_time', models.TimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_reminders', to='customers.customer')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_reminders', to='inventory.medicine')),
            ],
            options={
                'ordering': ['refill_date', 'refill_time'],
            },
        ),
    ]
