--
-- PostgreSQL database dump
--

\restrict Jg1dnvEIA0Ck9lpZdxaHCJhryJ9kpZLB6gc6xymuGJsAJHGhgTLI7vEsYZOhdZI

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

-- Started on 2026-08-20 11:39:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 265 (class 1259 OID 18104)
-- Name: accounts_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_userprofile (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_userprofile OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 18103)
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16412)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16411)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16420)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16419)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16406)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16405)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16426)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16434)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16433)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16425)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16440)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16439)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16527)
-- Name: customers_customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers_customer (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    address text NOT NULL,
    loyalty_points integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    blood_pressure_diastolic smallint,
    blood_pressure_systolic smallint,
    has_diabetes boolean NOT NULL,
    membership character varying(10) NOT NULL,
    CONSTRAINT customers_customer_blood_pressure_diastolic_check CHECK ((blood_pressure_diastolic >= 0)),
    CONSTRAINT customers_customer_blood_pressure_systolic_check CHECK ((blood_pressure_systolic >= 0))
);


ALTER TABLE public.customers_customer OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16526)
-- Name: customers_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 18049)
-- Name: customers_customermedicine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers_customermedicine (
    id bigint NOT NULL,
    dose character varying(100) NOT NULL,
    schedule character varying(255) NOT NULL,
    is_sensitive boolean NOT NULL,
    permission_status character varying(20) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    customer_id bigint NOT NULL,
    medicine_id bigint NOT NULL
);


ALTER TABLE public.customers_customermedicine OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 18048)
-- Name: customers_customermedicine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers_customermedicine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_customermedicine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 18143)
-- Name: customers_medicinerefillreminder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers_medicinerefillreminder (
    id bigint NOT NULL,
    refill_date date NOT NULL,
    refill_time time without time zone NOT NULL,
    is_active boolean NOT NULL,
    note character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    customer_id bigint NOT NULL,
    medicine_id bigint NOT NULL
);


ALTER TABLE public.customers_medicinerefillreminder OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 18142)
-- Name: customers_medicinerefillreminder_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers_medicinerefillreminder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_medicinerefillreminder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 18057)
-- Name: customers_medicinereminder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers_medicinereminder (
    id bigint NOT NULL,
    reminder_time time without time zone NOT NULL,
    days_of_week character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    customer_medicine_id bigint NOT NULL
);


ALTER TABLE public.customers_medicinereminder OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 18056)
-- Name: customers_medicinereminder_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers_medicinereminder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_medicinereminder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16498)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16497)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16398)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16397)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 16678)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 18081)
-- Name: interactions_druginteraction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interactions_druginteraction (
    id bigint NOT NULL,
    severity character varying(10) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    medicine_a_id bigint NOT NULL,
    medicine_b_id bigint NOT NULL,
    CONSTRAINT different_medicines_in_interaction CHECK ((NOT (medicine_a_id = medicine_b_id)))
);


ALTER TABLE public.interactions_druginteraction OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 18080)
-- Name: interactions_druginteraction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interactions_druginteraction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interactions_druginteraction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16538)
-- Name: inventory_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.inventory_category OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16537)
-- Name: inventory_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 16689)
-- Name: inventory_inventory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_inventory (
    id bigint NOT NULL,
    current_stock integer NOT NULL,
    minimum_stock integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    medicine_id bigint NOT NULL,
    CONSTRAINT inventory_inventory_current_stock_check CHECK ((current_stock >= 0)),
    CONSTRAINT inventory_inventory_minimum_stock_check CHECK ((minimum_stock >= 0))
);


ALTER TABLE public.inventory_inventory OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 16688)
-- Name: inventory_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 16706)
-- Name: inventory_inventorytransaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_inventorytransaction (
    id bigint NOT NULL,
    transaction_type character varying(3) NOT NULL,
    quantity integer NOT NULL,
    previous_stock integer NOT NULL,
    new_stock integer NOT NULL,
    note character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    inventory_id bigint NOT NULL,
    CONSTRAINT inventory_inventorytransaction_new_stock_check CHECK ((new_stock >= 0)),
    CONSTRAINT inventory_inventorytransaction_previous_stock_check CHECK ((previous_stock >= 0)),
    CONSTRAINT inventory_inventorytransaction_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.inventory_inventorytransaction OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 16705)
-- Name: inventory_inventorytransaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_inventorytransaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_inventorytransaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 16580)
-- Name: inventory_medicine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_medicine (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    generic_name character varying(255) NOT NULL,
    manufacturer character varying(255) NOT NULL,
    strength character varying(100) NOT NULL,
    dosage_form character varying(20) NOT NULL,
    pc_price numeric(10,2) NOT NULL,
    strip_price numeric(10,2) NOT NULL,
    box_price numeric(10,2) NOT NULL,
    minimum_stock integer NOT NULL,
    expiry_date date NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    pcs_per_strip integer NOT NULL,
    strips_per_box integer NOT NULL,
    cost_price numeric(10,2) NOT NULL,
    supplier_id bigint,
    medicine_group_id bigint,
    CONSTRAINT inventory_medicine_minimum_stock_check CHECK ((minimum_stock >= 0)),
    CONSTRAINT inventory_medicine_pcs_per_strip_check CHECK ((pcs_per_strip >= 0)),
    CONSTRAINT inventory_medicine_strips_per_box_check CHECK ((strips_per_box >= 0)),
    CONSTRAINT medicine_box_price_gte_strip_price CHECK ((box_price >= strip_price)),
    CONSTRAINT medicine_strip_price_gte_pc_price CHECK ((strip_price >= pc_price))
);


ALTER TABLE public.inventory_medicine OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16579)
-- Name: inventory_medicine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_medicine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_medicine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 18119)
-- Name: inventory_medicinegroup; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_medicinegroup (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.inventory_medicinegroup OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 18118)
-- Name: inventory_medicinegroup_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_medicinegroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_medicinegroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 18163)
-- Name: inventory_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_notification (
    id bigint NOT NULL,
    notification_type character varying(20) NOT NULL,
    severity character varying(10) NOT NULL,
    title character varying(255) NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    medicine_id bigint
);


ALTER TABLE public.inventory_notification OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 18162)
-- Name: inventory_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16548)
-- Name: inventory_supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_supplier (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    contact_person character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    address text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.inventory_supplier OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16547)
-- Name: inventory_supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 16601)
-- Name: purchases_purchase; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchases_purchase (
    id bigint NOT NULL,
    invoice_number character varying(50) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    discount numeric(12,2) NOT NULL,
    payable_amount numeric(12,2) NOT NULL,
    purchase_date date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    supplier_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.purchases_purchase OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16600)
-- Name: purchases_purchase_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchases_purchase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchases_purchase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 16609)
-- Name: purchases_purchaseitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchases_purchaseitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    expiry_date date,
    manufactured_date date,
    purchase_id bigint NOT NULL,
    medicine_id bigint,
    CONSTRAINT purchases_purchaseitem_quantity_554f21e6_check CHECK ((quantity >= 0))
);


ALTER TABLE public.purchases_purchaseitem OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 16608)
-- Name: purchases_purchaseitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchases_purchaseitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchases_purchaseitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 16640)
-- Name: sales_sale; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sales_sale (
    id bigint NOT NULL,
    invoice_number character varying(50) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    discount numeric(12,2) NOT NULL,
    payable_amount numeric(12,2) NOT NULL,
    payment_method character varying(10) NOT NULL,
    sale_date date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    customer_id bigint,
    user_id integer NOT NULL
);


ALTER TABLE public.sales_sale OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 16639)
-- Name: sales_sale_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sales_sale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_sale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 16648)
-- Name: sales_saleitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sales_saleitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    sale_id bigint NOT NULL,
    medicine_id bigint NOT NULL,
    unit_type character varying(10) NOT NULL,
    CONSTRAINT sales_saleitem_quantity_ece0f3cd_check CHECK ((quantity >= 0))
);


ALTER TABLE public.sales_saleitem OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 16647)
-- Name: sales_saleitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sales_saleitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_saleitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 18031)
-- Name: sales_salepayment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sales_salepayment (
    id bigint NOT NULL,
    payment_method character varying(10) NOT NULL,
    amount numeric(12,2) NOT NULL,
    sale_id bigint NOT NULL
);


ALTER TABLE public.sales_salepayment OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 18030)
-- Name: sales_salepayment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sales_salepayment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_salepayment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5260 (class 0 OID 18104)
-- Dependencies: 265
-- Data for Name: accounts_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_userprofile (id, role, user_id) FROM stdin;
1	admin	1
2	admin	2
3	pharmacist	3
\.


--
-- TOC entry 5219 (class 0 OID 16412)
-- Dependencies: 224
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5221 (class 0 OID 16420)
-- Dependencies: 226
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5217 (class 0 OID 16406)
-- Dependencies: 222
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add category	7	add_category
26	Can change category	7	change_category
27	Can delete category	7	delete_category
28	Can view category	7	view_category
29	Can add supplier	10	add_supplier
30	Can change supplier	10	change_supplier
31	Can delete supplier	10	delete_supplier
32	Can view supplier	10	view_supplier
33	Can add product	9	add_product
34	Can change product	9	change_product
35	Can delete product	9	delete_product
36	Can view product	9	view_product
37	Can add medicine	8	add_medicine
38	Can change medicine	8	change_medicine
39	Can delete medicine	8	delete_medicine
40	Can view medicine	8	view_medicine
41	Can add customer	11	add_customer
42	Can change customer	11	change_customer
43	Can delete customer	11	delete_customer
44	Can view customer	11	view_customer
45	Can add sale	12	add_sale
46	Can change sale	12	change_sale
47	Can delete sale	12	delete_sale
48	Can view sale	12	view_sale
49	Can add sale item	13	add_saleitem
50	Can change sale item	13	change_saleitem
51	Can delete sale item	13	delete_saleitem
52	Can view sale item	13	view_saleitem
53	Can add purchase	14	add_purchase
54	Can change purchase	14	change_purchase
55	Can delete purchase	14	delete_purchase
56	Can view purchase	14	view_purchase
57	Can add purchase item	15	add_purchaseitem
58	Can change purchase item	15	change_purchaseitem
59	Can delete purchase item	15	delete_purchaseitem
60	Can view purchase item	15	view_purchaseitem
61	Can add inventory	16	add_inventory
62	Can change inventory	16	change_inventory
63	Can delete inventory	16	delete_inventory
64	Can view inventory	16	view_inventory
65	Can add inventory transaction	17	add_inventorytransaction
66	Can change inventory transaction	17	change_inventorytransaction
67	Can delete inventory transaction	17	delete_inventorytransaction
68	Can view inventory transaction	17	view_inventorytransaction
69	Can add sale payment	18	add_salepayment
70	Can change sale payment	18	change_salepayment
71	Can delete sale payment	18	delete_salepayment
72	Can view sale payment	18	view_salepayment
73	Can add customer medicine	19	add_customermedicine
74	Can change customer medicine	19	change_customermedicine
75	Can delete customer medicine	19	delete_customermedicine
76	Can view customer medicine	19	view_customermedicine
77	Can add medicine reminder	20	add_medicinereminder
78	Can change medicine reminder	20	change_medicinereminder
79	Can delete medicine reminder	20	delete_medicinereminder
80	Can view medicine reminder	20	view_medicinereminder
81	Can add drug interaction	21	add_druginteraction
82	Can change drug interaction	21	change_druginteraction
83	Can delete drug interaction	21	delete_druginteraction
84	Can view drug interaction	21	view_druginteraction
85	Can add user profile	22	add_userprofile
86	Can change user profile	22	change_userprofile
87	Can delete user profile	22	delete_userprofile
88	Can view user profile	22	view_userprofile
89	Can add medicine group	23	add_medicinegroup
90	Can change medicine group	23	change_medicinegroup
91	Can delete medicine group	23	delete_medicinegroup
92	Can view medicine group	23	view_medicinegroup
93	Can add medicine refill reminder	24	add_medicinerefillreminder
94	Can change medicine refill reminder	24	change_medicinerefillreminder
95	Can delete medicine refill reminder	24	delete_medicinerefillreminder
96	Can view medicine refill reminder	24	view_medicinerefillreminder
97	Can add notification	25	add_notification
98	Can change notification	25	change_notification
99	Can delete notification	25	delete_notification
100	Can view notification	25	view_notification
\.


--
-- TOC entry 5223 (class 0 OID 16426)
-- Dependencies: 228
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1500000$BcxZbQB9xRewWQHQ2tKWEa$U+CcG4MfmStAzMG46pprOu3PHL6VxLwSL5UrpIopMZM=	2026-08-19 23:24:46.692526+06	t	admin			admin@pravo.com	t	t	2026-08-13 15:37:07.413834+06
2	pbkdf2_sha256$1500000$4rmY4ya01htYhEMZfn3b8F$yM9NLj90u87J+gAwxBlw8gPTKvJjdeqNph2HAP8CEYI=	\N	f	admin2			admin2@pharvo.com	f	f	2026-08-20 01:22:26.309457+06
3	pbkdf2_sha256$1500000$PiGfLZNksh5MXYovsTrxTd$Dp4aobHCSql9zSTnKCnOca1hwWqv3rm5Pml6yt5J2B0=	\N	f	pharmacist1			newpharmacist@pharvo.com	f	t	2026-08-20 01:22:45.557648+06
\.


--
-- TOC entry 5225 (class 0 OID 16434)
-- Dependencies: 230
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5227 (class 0 OID 16440)
-- Dependencies: 232
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5231 (class 0 OID 16527)
-- Dependencies: 236
-- Data for Name: customers_customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers_customer (id, name, phone, email, address, loyalty_points, created_at, blood_pressure_diastolic, blood_pressure_systolic, has_diabetes, membership) FROM stdin;
1	Rahim Uddin	01711111111	rahim@example.com	Dhaka	750	2026-08-20 00:18:33.522443+06	80	120	t	GOLD
2	Rahim Uddin	01711111112	rahim@example.com	Dhaka	750	2026-08-20 01:52:10.463364+06	80	120	f	GOLD
\.


--
-- TOC entry 5254 (class 0 OID 18049)
-- Dependencies: 259
-- Data for Name: customers_customermedicine; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers_customermedicine (id, dose, schedule, is_sensitive, permission_status, notes, created_at, updated_at, customer_id, medicine_id) FROM stdin;
1	1 tablet	After breakfast and dinner	f	NOT_REQUIRED	Take with water	2026-08-20 00:18:54.491044+06	2026-08-20 00:18:54.491054+06	1	1
2	1 tablet	As prescribed	t	APPROVED	Doctor permission verified	2026-08-20 00:19:37.349028+06	2026-08-20 00:19:37.349039+06	1	1
\.


--
-- TOC entry 5264 (class 0 OID 18143)
-- Dependencies: 269
-- Data for Name: customers_medicinerefillreminder; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers_medicinerefillreminder (id, refill_date, refill_time, is_active, note, created_at, updated_at, customer_id, medicine_id) FROM stdin;
1	2026-08-25	10:30:00	t	Monthly medicine refill	2026-08-20 10:38:43.152819+06	2026-08-20 10:38:43.152832+06	1	1
\.


--
-- TOC entry 5256 (class 0 OID 18057)
-- Dependencies: 261
-- Data for Name: customers_medicinereminder; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers_medicinereminder (id, reminder_time, days_of_week, is_active, created_at, customer_medicine_id) FROM stdin;
1	08:00:00	DAILY	t	2026-08-20 00:19:09.664348+06	1
2	20:00:00	DAILY	t	2026-08-20 00:19:16.332604+06	1
\.


--
-- TOC entry 5229 (class 0 OID 16498)
-- Dependencies: 234
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-08-20 00:32:52.877352+06	1	Ace 500mg 500 mg (TABLET)	2	[{"changed": {"fields": ["Name", "Manufacturer", "Pcs per strip", "Strips per box", "Minimum stock"]}}]	8	1
2	2026-08-20 00:36:30.419799+06	2	Napa 500mg (TABLET)	1	[{"added": {}}]	8	1
\.


--
-- TOC entry 5215 (class 0 OID 16398)
-- Dependencies: 220
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	inventory	category
8	inventory	medicine
9	inventory	product
10	inventory	supplier
11	customers	customer
12	sales	sale
13	sales	saleitem
14	purchases	purchase
15	purchases	purchaseitem
16	inventory	inventory
17	inventory	inventorytransaction
18	sales	salepayment
19	customers	customermedicine
20	customers	medicinereminder
21	interactions	druginteraction
22	accounts	userprofile
23	inventory	medicinegroup
24	customers	medicinerefillreminder
25	inventory	notification
\.


--
-- TOC entry 5213 (class 0 OID 16390)
-- Dependencies: 218
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-13 14:57:24.382116+06
2	auth	0001_initial	2026-08-13 14:57:24.428783+06
3	admin	0001_initial	2026-08-13 14:57:24.443979+06
4	admin	0002_logentry_remove_auto_add	2026-08-13 14:57:24.449041+06
5	admin	0003_logentry_add_action_flag_choices	2026-08-13 14:57:24.452672+06
6	contenttypes	0002_remove_content_type_name	2026-08-13 14:57:24.460406+06
7	auth	0002_alter_permission_name_max_length	2026-08-13 14:57:24.465348+06
8	auth	0003_alter_user_email_max_length	2026-08-13 14:57:24.469539+06
9	auth	0004_alter_user_username_opts	2026-08-13 14:57:24.473367+06
10	auth	0005_alter_user_last_login_null	2026-08-13 14:57:24.477275+06
11	auth	0006_require_contenttypes_0002	2026-08-13 14:57:24.478062+06
12	auth	0007_alter_validators_add_error_messages	2026-08-13 14:57:24.482538+06
13	auth	0008_alter_user_username_max_length	2026-08-13 14:57:24.489369+06
14	auth	0009_alter_user_last_name_max_length	2026-08-13 14:57:24.493778+06
15	auth	0010_alter_group_name_max_length	2026-08-13 14:57:24.499259+06
16	auth	0011_update_proxy_permissions	2026-08-13 14:57:24.503329+06
17	auth	0012_alter_user_first_name_max_length	2026-08-13 14:57:24.506979+06
18	customers	0001_initial	2026-08-13 14:57:24.514517+06
19	inventory	0001_initial	2026-08-13 14:57:24.538735+06
20	inventory	0002_medicine	2026-08-13 14:57:24.554305+06
21	purchases	0001_initial	2026-08-13 14:57:24.591285+06
22	sales	0001_initial	2026-08-13 14:57:24.624958+06
23	sessions	0001_initial	2026-08-13 14:57:24.632395+06
24	inventory	0003_inventory_and_more	2026-08-13 16:45:41.922872+06
25	inventory	0004_inventorytransaction	2026-08-13 17:00:05.525856+06
26	purchases	0002_remove_purchaseitem_product_purchaseitem_medicine_and_more	2026-08-14 01:46:24.569056+06
27	sales	0002_convert_product_to_medicine	2026-08-14 03:16:55.650132+06
28	sales	0003_convert_saleitem_to_medicine_schema	2026-08-14 03:35:08.816208+06
29	inventory	0005_delete_product	2026-08-14 04:02:17.913968+06
30	inventory	0006_medicine_pcs_per_strip_medicine_strips_per_box	2026-08-19 23:44:59.795628+06
31	sales	0004_alter_sale_options_saleitem_unit_type_and_more	2026-08-19 23:44:59.885794+06
32	customers	0002_customer_blood_pressure_diastolic_and_more	2026-08-20 00:17:29.706548+06
33	interactions	0001_initial	2026-08-20 00:28:40.908196+06
34	accounts	0001_initial	2026-08-20 01:19:36.181873+06
35	customers	0003_alter_customer_membership	2026-08-20 01:37:33.801969+06
36	inventory	0007_medicinegroup_medicine_cost_price_medicine_supplier_and_more	2026-08-20 02:51:55.914937+06
37	sales	0005_alter_sale_payment_method_and_more	2026-08-20 03:10:54.663682+06
38	customers	0004_medicinerefillreminder	2026-08-20 10:31:46.593708+06
39	inventory	0008_notification	2026-08-20 10:48:25.631521+06
\.


--
-- TOC entry 5246 (class 0 OID 16678)
-- Dependencies: 251
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
1wq3mf4orlj0f25l00bbjwfhshcm81ju	.eJxVjMsOgjAQAP9lz6aBvsvRu99AdruLRQ1NKJyM_25IOOh1ZjJvGHHfyrg3WceZYYAeLr-MMD9lOQQ_cLlXleuyrTOpI1GnbepWWV7Xs_0bFGwFBoiTt1OfTXQkXaCYNGubEvchdV44OKtTFM2TMU6C90g5eZJokazVEeHzBdJBN5c:1wwk1u:unhAsRshMJunC4nQkr-UsUAxnevB8KlCqvgwCOQD7fQ	2026-09-02 23:24:46.694287+06
\.


--
-- TOC entry 5258 (class 0 OID 18081)
-- Dependencies: 263
-- Data for Name: interactions_druginteraction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.interactions_druginteraction (id, severity, description, created_at, updated_at, medicine_a_id, medicine_b_id) FROM stdin;
1	SEVERE	Concurrent use may increase the risk of adverse effects.	2026-08-20 00:36:44.997018+06	2026-08-20 00:36:44.997028+06	1	2
\.


--
-- TOC entry 5233 (class 0 OID 16538)
-- Dependencies: 238
-- Data for Name: inventory_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory_category (id, name, description) FROM stdin;
1	Tablet	
2	Napa 500mg	
\.


--
-- TOC entry 5248 (class 0 OID 16689)
-- Dependencies: 253
-- Data for Name: inventory_inventory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory_inventory (id, current_stock, minimum_stock, updated_at, medicine_id) FROM stdin;
2	25	10	2026-08-20 02:59:35.023891+06	2
1	151	20	2026-08-20 03:12:10.774645+06	1
\.


--
-- TOC entry 5250 (class 0 OID 16706)
-- Dependencies: 255
-- Data for Name: inventory_inventorytransaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory_inventorytransaction (id, transaction_type, quantity, previous_stock, new_stock, note, created_at, inventory_id) FROM stdin;
1	IN	50	10	60	New stock received	2026-08-13 17:16:03.226711+06	1
2	IN	50	60	110	New stock received	2026-08-13 17:18:43.512651+06	1
3	OUT	10	110	100	Medicine sold	2026-08-13 17:20:03.847825+06	1
4	OUT	10	100	90	Medicine sold	2026-08-13 17:20:47.173139+06	1
5	OUT	10	90	80	Medicine sold	2026-08-13 17:20:48.959857+06	1
6	IN	15	80	95	New stock received	2026-08-13 17:21:44.180468+06	1
7	IN	15	95	110	New stock received	2026-08-13 17:21:55.716596+06	1
8	OUT	70	110	40	Medicine sold	2026-08-13 17:22:57.246496+06	1
9	IN	50	40	90	New stock received	2026-08-14 00:23:56.560047+06	1
10	OUT	80	90	10	Sold Medichine	2026-08-14 00:25:28.575574+06	1
11	OUT	10	10	0	Medicine sold	2026-08-14 00:27:07.460877+06	1
12	IN	50	0	50	New stock received	2026-08-14 00:57:32.107896+06	1
13	OUT	10	50	40	Medicine sold	2026-08-14 00:57:52.951642+06	1
14	IN	50	40	90	Purchase #PUR-002	2026-08-14 01:59:54.552602+06	1
15	IN	50	90	140	Purchase #PUR-003	2026-08-14 02:04:12.234644+06	1
16	OUT	20	140	120	POS Sale INV-1E1239235E	2026-08-19 23:56:50.194549+06	1
17	OUT	5	120	115	POS Sale INV-7EA4CF5A2B	2026-08-20 00:06:04.225646+06	1
18	OUT	2	115	113	POS Sale INV-8A04832953	2026-08-20 00:06:32.094088+06	1
19	OUT	1	113	112	POS Sale INV-CAAC242794	2026-08-20 00:08:30.758797+06	1
20	OUT	1	112	111	POS Sale INV-C7800C5878	2026-08-20 00:09:27.397142+06	1
21	IN	50	111	161	Purchase #PUR-004	2026-08-20 02:59:35.018091+06	1
22	IN	25	0	25	Purchase #PUR-004	2026-08-20 02:59:35.024433+06	2
23	OUT	5	161	156	POS Sale INV-DF042A9770	2026-08-20 03:11:55.791668+06	1
24	OUT	5	156	151	POS Sale INV-74FA77DC9A	2026-08-20 03:12:10.7754+06	1
\.


--
-- TOC entry 5237 (class 0 OID 16580)
-- Dependencies: 242
-- Data for Name: inventory_medicine; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory_medicine (id, name, generic_name, manufacturer, strength, dosage_form, pc_price, strip_price, box_price, minimum_stock, expiry_date, is_active, created_at, updated_at, category_id, pcs_per_strip, strips_per_box, cost_price, supplier_id, medicine_group_id) FROM stdin;
1	Ace 500mg	Paracetamol	Square Ltd.	500 mg	TABLET	2.00	20.00	200.00	20	2027-12-31	t	2026-08-13 16:04:50.983644+06	2026-08-20 00:32:52.876053+06	1	10	20	0.00	\N	\N
2	Napa	Paracetamol	Beximco LTD.	500mg	TABLET	2.00	20.00	200.00	10	2027-12-31	t	2026-08-20 00:36:30.417592+06	2026-08-20 00:36:30.417598+06	1	10	20	0.00	\N	\N
\.


--
-- TOC entry 5262 (class 0 OID 18119)
-- Dependencies: 267
-- Data for Name: inventory_medicinegroup; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory_medicinegroup (id, name, description) FROM stdin;
1	Analgesics	Pain and fever medicines
\.


--
-- TOC entry 5266 (class 0 OID 18163)
-- Dependencies: 271
-- Data for Name: inventory_notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory_notification (id, notification_type, severity, title, message, is_read, created_at, medicine_id) FROM stdin;
1	low_stock	warning	Low Stock Alert	Napa stock is below the minimum level.	f	2026-08-20 10:49:39.789791+06	1
2	out_of_stock	critical	Out of Stock	Napa is currently out of stock.	f	2026-08-20 10:49:47.400201+06	1
3	expired	critical	Medicine Expired	This medicine has expired.	f	2026-08-20 10:49:53.19226+06	1
4	near_expiry	warning	Medicine Near Expiry	This medicine will expire soon.	f	2026-08-20 10:49:58.513513+06	1
\.


--
-- TOC entry 5235 (class 0 OID 16548)
-- Dependencies: 240
-- Data for Name: inventory_supplier; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory_supplier (id, name, contact_person, phone, email, address, created_at) FROM stdin;
1	Mirpur Pharmaceuticals	Sumon	01304356466	sumon@example.com	Dhaka, Bangladesh	2026-08-14 01:26:39.017942+06
\.


--
-- TOC entry 5239 (class 0 OID 16601)
-- Dependencies: 244
-- Data for Name: purchases_purchase; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.purchases_purchase (id, invoice_number, total_amount, discount, payable_amount, purchase_date, created_at, supplier_id, user_id) FROM stdin;
4	PUR-002	100.00	0.00	100.00	2026-08-14	2026-08-14 01:59:54.544103+06	1	1
6	PUR-004	150.00	10.00	140.00	2026-08-20	2026-08-20 02:59:35.007425+06	1	1
\.


--
-- TOC entry 5241 (class 0 OID 16609)
-- Dependencies: 246
-- Data for Name: purchases_purchaseitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.purchases_purchaseitem (id, quantity, unit_price, subtotal, expiry_date, manufactured_date, purchase_id, medicine_id) FROM stdin;
1	50	2.00	100.00	2027-12-31	2026-01-01	4	1
3	50	2.00	100.00	2027-12-31	2026-01-01	6	1
4	25	2.00	50.00	2027-10-31	2026-01-01	6	2
\.


--
-- TOC entry 5243 (class 0 OID 16640)
-- Dependencies: 248
-- Data for Name: sales_sale; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sales_sale (id, invoice_number, total_amount, discount, payable_amount, payment_method, sale_date, created_at, customer_id, user_id) FROM stdin;
1	INV-1E1239235E	40.00	20.00	20.00	SPLIT	2026-08-19	2026-08-19 23:56:50.17918+06	\N	1
2	INV-7EA4CF5A2B	10.00	0.00	10.00	CASH	2026-08-20	2026-08-20 00:06:04.221439+06	\N	1
3	INV-8A04832953	40.00	0.00	40.00	CASH	2026-08-20	2026-08-20 00:06:32.090871+06	\N	1
4	INV-CAAC242794	200.00	0.00	200.00	CASH	2026-08-20	2026-08-20 00:08:30.75502+06	\N	1
5	INV-C7800C5878	200.00	0.00	200.00	CASH	2026-08-20	2026-08-20 00:09:27.393423+06	\N	1
6	INV-DF042A9770	10.00	0.00	10.00	BKASH	2026-08-20	2026-08-20 03:11:55.787133+06	\N	1
7	INV-74FA77DC9A	10.00	0.00	10.00	NAGAD	2026-08-20	2026-08-20 03:12:10.771838+06	\N	1
\.


--
-- TOC entry 5245 (class 0 OID 16648)
-- Dependencies: 250
-- Data for Name: sales_saleitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sales_saleitem (id, quantity, unit_price, subtotal, sale_id, medicine_id, unit_type) FROM stdin;
1	2	20.00	40.00	1	1	STRIP
2	5	2.00	10.00	2	1	PC
3	2	20.00	40.00	3	1	STRIP
4	1	200.00	200.00	4	1	BOX
5	1	200.00	200.00	5	1	BOX
6	5	2.00	10.00	6	1	PC
7	5	2.00	10.00	7	1	PC
\.


--
-- TOC entry 5252 (class 0 OID 18031)
-- Dependencies: 257
-- Data for Name: sales_salepayment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sales_salepayment (id, payment_method, amount, sale_id) FROM stdin;
1	CASH	10.00	1
2	MOBILE	10.00	1
3	CASH	10.00	2
4	CASH	40.00	3
5	CASH	200.00	4
6	CASH	200.00	5
7	BKASH	10.00	6
8	NAGAD	10.00	7
\.


--
-- TOC entry 5272 (class 0 OID 0)
-- Dependencies: 264
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_userprofile_id_seq', 3, true);


--
-- TOC entry 5273 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5274 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5275 (class 0 OID 0)
-- Dependencies: 221
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 100, true);


--
-- TOC entry 5276 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5277 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- TOC entry 5278 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5279 (class 0 OID 0)
-- Dependencies: 235
-- Name: customers_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_customer_id_seq', 2, true);


--
-- TOC entry 5280 (class 0 OID 0)
-- Dependencies: 258
-- Name: customers_customermedicine_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_customermedicine_id_seq', 2, true);


--
-- TOC entry 5281 (class 0 OID 0)
-- Dependencies: 268
-- Name: customers_medicinerefillreminder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_medicinerefillreminder_id_seq', 1, true);


--
-- TOC entry 5282 (class 0 OID 0)
-- Dependencies: 260
-- Name: customers_medicinereminder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_medicinereminder_id_seq', 2, true);


--
-- TOC entry 5283 (class 0 OID 0)
-- Dependencies: 233
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 2, true);


--
-- TOC entry 5284 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 25, true);


--
-- TOC entry 5285 (class 0 OID 0)
-- Dependencies: 217
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 39, true);


--
-- TOC entry 5286 (class 0 OID 0)
-- Dependencies: 262
-- Name: interactions_druginteraction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.interactions_druginteraction_id_seq', 1, true);


--
-- TOC entry 5287 (class 0 OID 0)
-- Dependencies: 237
-- Name: inventory_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_category_id_seq', 2, true);


--
-- TOC entry 5288 (class 0 OID 0)
-- Dependencies: 252
-- Name: inventory_inventory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_inventory_id_seq', 2, true);


--
-- TOC entry 5289 (class 0 OID 0)
-- Dependencies: 254
-- Name: inventory_inventorytransaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_inventorytransaction_id_seq', 24, true);


--
-- TOC entry 5290 (class 0 OID 0)
-- Dependencies: 241
-- Name: inventory_medicine_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_medicine_id_seq', 2, true);


--
-- TOC entry 5291 (class 0 OID 0)
-- Dependencies: 266
-- Name: inventory_medicinegroup_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_medicinegroup_id_seq', 1, true);


--
-- TOC entry 5292 (class 0 OID 0)
-- Dependencies: 270
-- Name: inventory_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_notification_id_seq', 4, true);


--
-- TOC entry 5293 (class 0 OID 0)
-- Dependencies: 239
-- Name: inventory_supplier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_supplier_id_seq', 1, true);


--
-- TOC entry 5294 (class 0 OID 0)
-- Dependencies: 243
-- Name: purchases_purchase_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.purchases_purchase_id_seq', 6, true);


--
-- TOC entry 5295 (class 0 OID 0)
-- Dependencies: 245
-- Name: purchases_purchaseitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.purchases_purchaseitem_id_seq', 4, true);


--
-- TOC entry 5296 (class 0 OID 0)
-- Dependencies: 247
-- Name: sales_sale_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sales_sale_id_seq', 7, true);


--
-- TOC entry 5297 (class 0 OID 0)
-- Dependencies: 249
-- Name: sales_saleitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sales_saleitem_id_seq', 7, true);


--
-- TOC entry 5298 (class 0 OID 0)
-- Dependencies: 256
-- Name: sales_salepayment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sales_salepayment_id_seq', 8, true);


--
-- TOC entry 5012 (class 2606 OID 18108)
-- Name: accounts_userprofile accounts_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_pkey PRIMARY KEY (id);


--
-- TOC entry 5016 (class 2606 OID 18110)
-- Name: accounts_userprofile accounts_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_key UNIQUE (user_id);


--
-- TOC entry 4905 (class 2606 OID 16524)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4910 (class 2606 OID 16455)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4913 (class 2606 OID 16424)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 16416)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 16446)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4902 (class 2606 OID 16410)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4921 (class 2606 OID 16438)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4924 (class 2606 OID 16470)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4915 (class 2606 OID 16430)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4927 (class 2606 OID 16444)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4930 (class 2606 OID 16484)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4918 (class 2606 OID 16519)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4937 (class 2606 OID 16535)
-- Name: customers_customer customers_customer_phone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_customer
    ADD CONSTRAINT customers_customer_phone_key UNIQUE (phone);


--
-- TOC entry 4939 (class 2606 OID 16533)
-- Name: customers_customer customers_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_customer
    ADD CONSTRAINT customers_customer_pkey PRIMARY KEY (id);


--
-- TOC entry 5001 (class 2606 OID 18055)
-- Name: customers_customermedicine customers_customermedicine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_customermedicine
    ADD CONSTRAINT customers_customermedicine_pkey PRIMARY KEY (id);


--
-- TOC entry 5026 (class 2606 OID 18147)
-- Name: customers_medicinerefillreminder customers_medicinerefillreminder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_medicinerefillreminder
    ADD CONSTRAINT customers_medicinerefillreminder_pkey PRIMARY KEY (id);


--
-- TOC entry 5004 (class 2606 OID 18061)
-- Name: customers_medicinereminder customers_medicinereminder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_medicinereminder
    ADD CONSTRAINT customers_medicinereminder_pkey PRIMARY KEY (id);


--
-- TOC entry 4933 (class 2606 OID 16505)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4895 (class 2606 OID 16404)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4897 (class 2606 OID 16402)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4893 (class 2606 OID 16396)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4980 (class 2606 OID 16684)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5008 (class 2606 OID 18088)
-- Name: interactions_druginteraction interactions_druginteraction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interactions_druginteraction
    ADD CONSTRAINT interactions_druginteraction_pkey PRIMARY KEY (id);


--
-- TOC entry 4942 (class 2606 OID 16546)
-- Name: inventory_category inventory_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_category
    ADD CONSTRAINT inventory_category_name_key UNIQUE (name);


--
-- TOC entry 4944 (class 2606 OID 16544)
-- Name: inventory_category inventory_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_category
    ADD CONSTRAINT inventory_category_pkey PRIMARY KEY (id);


--
-- TOC entry 4985 (class 2606 OID 16697)
-- Name: inventory_inventory inventory_inventory_medicine_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_inventory
    ADD CONSTRAINT inventory_inventory_medicine_id_key UNIQUE (medicine_id);


--
-- TOC entry 4987 (class 2606 OID 16695)
-- Name: inventory_inventory inventory_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_inventory
    ADD CONSTRAINT inventory_inventory_pkey PRIMARY KEY (id);


--
-- TOC entry 4992 (class 2606 OID 16713)
-- Name: inventory_inventorytransaction inventory_inventorytransaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_inventorytransaction
    ADD CONSTRAINT inventory_inventorytransaction_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 16589)
-- Name: inventory_medicine inventory_medicine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_medicine
    ADD CONSTRAINT inventory_medicine_pkey PRIMARY KEY (id);


--
-- TOC entry 5019 (class 2606 OID 18127)
-- Name: inventory_medicinegroup inventory_medicinegroup_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_medicinegroup
    ADD CONSTRAINT inventory_medicinegroup_name_key UNIQUE (name);


--
-- TOC entry 5021 (class 2606 OID 18125)
-- Name: inventory_medicinegroup inventory_medicinegroup_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_medicinegroup
    ADD CONSTRAINT inventory_medicinegroup_pkey PRIMARY KEY (id);


--
-- TOC entry 5034 (class 2606 OID 18169)
-- Name: inventory_notification inventory_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_notification
    ADD CONSTRAINT inventory_notification_pkey PRIMARY KEY (id);


--
-- TOC entry 4946 (class 2606 OID 16554)
-- Name: inventory_supplier inventory_supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_supplier
    ADD CONSTRAINT inventory_supplier_pkey PRIMARY KEY (id);


--
-- TOC entry 4958 (class 2606 OID 16607)
-- Name: purchases_purchase purchases_purchase_invoice_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchases_purchase
    ADD CONSTRAINT purchases_purchase_invoice_number_key UNIQUE (invoice_number);


--
-- TOC entry 4960 (class 2606 OID 16605)
-- Name: purchases_purchase purchases_purchase_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchases_purchase
    ADD CONSTRAINT purchases_purchase_pkey PRIMARY KEY (id);


--
-- TOC entry 4965 (class 2606 OID 16613)
-- Name: purchases_purchaseitem purchases_purchaseitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchases_purchaseitem
    ADD CONSTRAINT purchases_purchaseitem_pkey PRIMARY KEY (id);


--
-- TOC entry 4970 (class 2606 OID 16646)
-- Name: sales_sale sales_sale_invoice_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_invoice_number_key UNIQUE (invoice_number);


--
-- TOC entry 4972 (class 2606 OID 16644)
-- Name: sales_sale sales_sale_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_pkey PRIMARY KEY (id);


--
-- TOC entry 4976 (class 2606 OID 16652)
-- Name: sales_saleitem sales_saleitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT sales_saleitem_pkey PRIMARY KEY (id);


--
-- TOC entry 4994 (class 2606 OID 18035)
-- Name: sales_salepayment sales_salepayment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_salepayment
    ADD CONSTRAINT sales_salepayment_pkey PRIMARY KEY (id);


--
-- TOC entry 5010 (class 2606 OID 18090)
-- Name: interactions_druginteraction unique_drug_interaction_pair; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interactions_druginteraction
    ADD CONSTRAINT unique_drug_interaction_pair UNIQUE (medicine_a_id, medicine_b_id);


--
-- TOC entry 4997 (class 2606 OID 18037)
-- Name: sales_salepayment unique_payment_method_per_sale; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_salepayment
    ADD CONSTRAINT unique_payment_method_per_sale UNIQUE (sale_id, payment_method);


--
-- TOC entry 5013 (class 1259 OID 18116)
-- Name: accounts_userprofile_role_f557a06b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_userprofile_role_f557a06b ON public.accounts_userprofile USING btree (role);


--
-- TOC entry 5014 (class 1259 OID 18117)
-- Name: accounts_userprofile_role_f557a06b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_userprofile_role_f557a06b_like ON public.accounts_userprofile USING btree (role varchar_pattern_ops);


--
-- TOC entry 4903 (class 1259 OID 16525)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4908 (class 1259 OID 16466)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4911 (class 1259 OID 16467)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4898 (class 1259 OID 16452)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4919 (class 1259 OID 16482)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4922 (class 1259 OID 16481)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4925 (class 1259 OID 16496)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4928 (class 1259 OID 16495)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4916 (class 1259 OID 16520)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4935 (class 1259 OID 16536)
-- Name: customers_customer_phone_01182399_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_customer_phone_01182399_like ON public.customers_customer USING btree (phone varchar_pattern_ops);


--
-- TOC entry 4998 (class 1259 OID 18072)
-- Name: customers_customermedicine_customer_id_462b1e7b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_customermedicine_customer_id_462b1e7b ON public.customers_customermedicine USING btree (customer_id);


--
-- TOC entry 4999 (class 1259 OID 18073)
-- Name: customers_customermedicine_medicine_id_803d7716; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_customermedicine_medicine_id_803d7716 ON public.customers_customermedicine USING btree (medicine_id);


--
-- TOC entry 5022 (class 1259 OID 18160)
-- Name: customers_medicinerefillreminder_customer_id_2cbce425; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_medicinerefillreminder_customer_id_2cbce425 ON public.customers_medicinerefillreminder USING btree (customer_id);


--
-- TOC entry 5023 (class 1259 OID 18159)
-- Name: customers_medicinerefillreminder_is_active_625916be; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_medicinerefillreminder_is_active_625916be ON public.customers_medicinerefillreminder USING btree (is_active);


--
-- TOC entry 5024 (class 1259 OID 18161)
-- Name: customers_medicinerefillreminder_medicine_id_f577da22; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_medicinerefillreminder_medicine_id_f577da22 ON public.customers_medicinerefillreminder USING btree (medicine_id);


--
-- TOC entry 5027 (class 1259 OID 18158)
-- Name: customers_medicinerefillreminder_refill_date_5ccd7456; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_medicinerefillreminder_refill_date_5ccd7456 ON public.customers_medicinerefillreminder USING btree (refill_date);


--
-- TOC entry 5002 (class 1259 OID 18079)
-- Name: customers_medicinereminder_customer_medicine_id_e03cf8d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_medicinereminder_customer_medicine_id_e03cf8d7 ON public.customers_medicinereminder USING btree (customer_medicine_id);


--
-- TOC entry 4931 (class 1259 OID 16516)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4934 (class 1259 OID 16517)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4978 (class 1259 OID 16686)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4981 (class 1259 OID 16685)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5005 (class 1259 OID 18101)
-- Name: interactions_druginteraction_medicine_a_id_63b1404a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX interactions_druginteraction_medicine_a_id_63b1404a ON public.interactions_druginteraction USING btree (medicine_a_id);


--
-- TOC entry 5006 (class 1259 OID 18102)
-- Name: interactions_druginteraction_medicine_b_id_18273300; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX interactions_druginteraction_medicine_b_id_18273300 ON public.interactions_druginteraction USING btree (medicine_b_id);


--
-- TOC entry 4940 (class 1259 OID 16565)
-- Name: inventory_category_name_c89a8bc0_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_category_name_c89a8bc0_like ON public.inventory_category USING btree (name varchar_pattern_ops);


--
-- TOC entry 4988 (class 1259 OID 16721)
-- Name: inventory_i_created_670884_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_i_created_670884_idx ON public.inventory_inventorytransaction USING btree (created_at);


--
-- TOC entry 4982 (class 1259 OID 16703)
-- Name: inventory_i_current_13b727_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_i_current_13b727_idx ON public.inventory_inventory USING btree (current_stock);


--
-- TOC entry 4983 (class 1259 OID 16704)
-- Name: inventory_i_minimum_c2e85e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_i_minimum_c2e85e_idx ON public.inventory_inventory USING btree (minimum_stock);


--
-- TOC entry 4989 (class 1259 OID 16720)
-- Name: inventory_i_transac_2eccee_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_i_transac_2eccee_idx ON public.inventory_inventorytransaction USING btree (transaction_type);


--
-- TOC entry 4990 (class 1259 OID 16719)
-- Name: inventory_inventorytransaction_inventory_id_90eecbc8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_inventorytransaction_inventory_id_90eecbc8 ON public.inventory_inventorytransaction USING btree (inventory_id);


--
-- TOC entry 4947 (class 1259 OID 16599)
-- Name: inventory_m_expiry__3d60fd_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_m_expiry__3d60fd_idx ON public.inventory_medicine USING btree (expiry_date);


--
-- TOC entry 4948 (class 1259 OID 16597)
-- Name: inventory_m_generic_acb93c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_m_generic_acb93c_idx ON public.inventory_medicine USING btree (generic_name);


--
-- TOC entry 4949 (class 1259 OID 16598)
-- Name: inventory_m_manufac_d4d4cb_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_m_manufac_d4d4cb_idx ON public.inventory_medicine USING btree (manufacturer);


--
-- TOC entry 4950 (class 1259 OID 16596)
-- Name: inventory_m_name_7f2fd2_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_m_name_7f2fd2_idx ON public.inventory_medicine USING btree (name);


--
-- TOC entry 4951 (class 1259 OID 16595)
-- Name: inventory_medicine_category_id_19734d4e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_medicine_category_id_19734d4e ON public.inventory_medicine USING btree (category_id);


--
-- TOC entry 4952 (class 1259 OID 18141)
-- Name: inventory_medicine_medicine_group_id_cf486ddb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_medicine_medicine_group_id_cf486ddb ON public.inventory_medicine USING btree (medicine_group_id);


--
-- TOC entry 4955 (class 1259 OID 18140)
-- Name: inventory_medicine_supplier_id_d39ab7fb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_medicine_supplier_id_d39ab7fb ON public.inventory_medicine USING btree (supplier_id);


--
-- TOC entry 5017 (class 1259 OID 18139)
-- Name: inventory_medicinegroup_name_b0f745a4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_medicinegroup_name_b0f745a4_like ON public.inventory_medicinegroup USING btree (name varchar_pattern_ops);


--
-- TOC entry 5028 (class 1259 OID 18179)
-- Name: inventory_n_is_read_8ccea4_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_n_is_read_8ccea4_idx ON public.inventory_notification USING btree (is_read);


--
-- TOC entry 5029 (class 1259 OID 18177)
-- Name: inventory_n_notific_ed75b1_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_n_notific_ed75b1_idx ON public.inventory_notification USING btree (notification_type);


--
-- TOC entry 5030 (class 1259 OID 18178)
-- Name: inventory_n_severit_8d3c0b_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_n_severit_8d3c0b_idx ON public.inventory_notification USING btree (severity);


--
-- TOC entry 5031 (class 1259 OID 18175)
-- Name: inventory_notification_is_read_05c878b8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_notification_is_read_05c878b8 ON public.inventory_notification USING btree (is_read);


--
-- TOC entry 5032 (class 1259 OID 18176)
-- Name: inventory_notification_medicine_id_b40d0b55; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX inventory_notification_medicine_id_b40d0b55 ON public.inventory_notification USING btree (medicine_id);


--
-- TOC entry 4956 (class 1259 OID 16624)
-- Name: purchases_purchase_invoice_number_1f630bb1_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX purchases_purchase_invoice_number_1f630bb1_like ON public.purchases_purchase USING btree (invoice_number varchar_pattern_ops);


--
-- TOC entry 4961 (class 1259 OID 16625)
-- Name: purchases_purchase_supplier_id_2d052a2a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX purchases_purchase_supplier_id_2d052a2a ON public.purchases_purchase USING btree (supplier_id);


--
-- TOC entry 4962 (class 1259 OID 16626)
-- Name: purchases_purchase_user_id_05c12ae8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX purchases_purchase_user_id_05c12ae8 ON public.purchases_purchase USING btree (user_id);


--
-- TOC entry 4963 (class 1259 OID 16728)
-- Name: purchases_purchaseitem_medicine_id_74a97fa7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX purchases_purchaseitem_medicine_id_74a97fa7 ON public.purchases_purchaseitem USING btree (medicine_id);


--
-- TOC entry 4966 (class 1259 OID 16638)
-- Name: purchases_purchaseitem_purchase_id_a7f96c61; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX purchases_purchaseitem_purchase_id_a7f96c61 ON public.purchases_purchaseitem USING btree (purchase_id);


--
-- TOC entry 4967 (class 1259 OID 16664)
-- Name: sales_sale_customer_id_2d66a408; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sales_sale_customer_id_2d66a408 ON public.sales_sale USING btree (customer_id);


--
-- TOC entry 4968 (class 1259 OID 16663)
-- Name: sales_sale_invoice_number_a14f1a3f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sales_sale_invoice_number_a14f1a3f_like ON public.sales_sale USING btree (invoice_number varchar_pattern_ops);


--
-- TOC entry 4973 (class 1259 OID 16665)
-- Name: sales_sale_user_id_c0f47f66; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sales_sale_user_id_c0f47f66 ON public.sales_sale USING btree (user_id);


--
-- TOC entry 4974 (class 1259 OID 17075)
-- Name: sales_saleitem_medicine_id_a5bd8707; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sales_saleitem_medicine_id_a5bd8707 ON public.sales_saleitem USING btree (medicine_id);


--
-- TOC entry 4977 (class 1259 OID 16677)
-- Name: sales_saleitem_sale_id_56e67045; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sales_saleitem_sale_id_56e67045 ON public.sales_saleitem USING btree (sale_id);


--
-- TOC entry 4995 (class 1259 OID 18043)
-- Name: sales_salepayment_sale_id_894e0b7b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX sales_salepayment_sale_id_894e0b7b ON public.sales_salepayment USING btree (sale_id);


--
-- TOC entry 5063 (class 2606 OID 18111)
-- Name: accounts_userprofile accounts_userprofile_user_id_92240672_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_92240672_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5036 (class 2606 OID 16461)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5037 (class 2606 OID 16456)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5035 (class 2606 OID 16447)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5038 (class 2606 OID 16476)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5039 (class 2606 OID 16471)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5040 (class 2606 OID 16490)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5041 (class 2606 OID 16485)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5058 (class 2606 OID 18062)
-- Name: customers_customermedicine customers_customerme_customer_id_462b1e7b_fk_customers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_customermedicine
    ADD CONSTRAINT customers_customerme_customer_id_462b1e7b_fk_customers FOREIGN KEY (customer_id) REFERENCES public.customers_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5059 (class 2606 OID 18067)
-- Name: customers_customermedicine customers_customerme_medicine_id_803d7716_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_customermedicine
    ADD CONSTRAINT customers_customerme_medicine_id_803d7716_fk_inventory FOREIGN KEY (medicine_id) REFERENCES public.inventory_medicine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5064 (class 2606 OID 18148)
-- Name: customers_medicinerefillreminder customers_medicinere_customer_id_2cbce425_fk_customers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_medicinerefillreminder
    ADD CONSTRAINT customers_medicinere_customer_id_2cbce425_fk_customers FOREIGN KEY (customer_id) REFERENCES public.customers_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5060 (class 2606 OID 18074)
-- Name: customers_medicinereminder customers_medicinere_customer_medicine_id_e03cf8d7_fk_customers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_medicinereminder
    ADD CONSTRAINT customers_medicinere_customer_medicine_id_e03cf8d7_fk_customers FOREIGN KEY (customer_medicine_id) REFERENCES public.customers_customermedicine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5065 (class 2606 OID 18153)
-- Name: customers_medicinerefillreminder customers_medicinere_medicine_id_f577da22_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers_medicinerefillreminder
    ADD CONSTRAINT customers_medicinere_medicine_id_f577da22_fk_inventory FOREIGN KEY (medicine_id) REFERENCES public.inventory_medicine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5042 (class 2606 OID 16506)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5043 (class 2606 OID 16511)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5061 (class 2606 OID 18091)
-- Name: interactions_druginteraction interactions_drugint_medicine_a_id_63b1404a_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interactions_druginteraction
    ADD CONSTRAINT interactions_drugint_medicine_a_id_63b1404a_fk_inventory FOREIGN KEY (medicine_a_id) REFERENCES public.inventory_medicine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5062 (class 2606 OID 18096)
-- Name: interactions_druginteraction interactions_drugint_medicine_b_id_18273300_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interactions_druginteraction
    ADD CONSTRAINT interactions_drugint_medicine_b_id_18273300_fk_inventory FOREIGN KEY (medicine_b_id) REFERENCES public.inventory_medicine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5055 (class 2606 OID 16698)
-- Name: inventory_inventory inventory_inventory_medicine_id_534caca4_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_inventory
    ADD CONSTRAINT inventory_inventory_medicine_id_534caca4_fk_inventory FOREIGN KEY (medicine_id) REFERENCES public.inventory_medicine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5056 (class 2606 OID 16714)
-- Name: inventory_inventorytransaction inventory_inventoryt_inventory_id_90eecbc8_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_inventorytransaction
    ADD CONSTRAINT inventory_inventoryt_inventory_id_90eecbc8_fk_inventory FOREIGN KEY (inventory_id) REFERENCES public.inventory_inventory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5044 (class 2606 OID 16590)
-- Name: inventory_medicine inventory_medicine_category_id_19734d4e_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_medicine
    ADD CONSTRAINT inventory_medicine_category_id_19734d4e_fk_inventory FOREIGN KEY (category_id) REFERENCES public.inventory_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5045 (class 2606 OID 18134)
-- Name: inventory_medicine inventory_medicine_medicine_group_id_cf486ddb_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_medicine
    ADD CONSTRAINT inventory_medicine_medicine_group_id_cf486ddb_fk_inventory FOREIGN KEY (medicine_group_id) REFERENCES public.inventory_medicinegroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5046 (class 2606 OID 18129)
-- Name: inventory_medicine inventory_medicine_supplier_id_d39ab7fb_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_medicine
    ADD CONSTRAINT inventory_medicine_supplier_id_d39ab7fb_fk_inventory FOREIGN KEY (supplier_id) REFERENCES public.inventory_supplier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5066 (class 2606 OID 18170)
-- Name: inventory_notification inventory_notificati_medicine_id_b40d0b55_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_notification
    ADD CONSTRAINT inventory_notificati_medicine_id_b40d0b55_fk_inventory FOREIGN KEY (medicine_id) REFERENCES public.inventory_medicine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5047 (class 2606 OID 16614)
-- Name: purchases_purchase purchases_purchase_supplier_id_2d052a2a_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchases_purchase
    ADD CONSTRAINT purchases_purchase_supplier_id_2d052a2a_fk_inventory FOREIGN KEY (supplier_id) REFERENCES public.inventory_supplier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5048 (class 2606 OID 16619)
-- Name: purchases_purchase purchases_purchase_user_id_05c12ae8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchases_purchase
    ADD CONSTRAINT purchases_purchase_user_id_05c12ae8_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5049 (class 2606 OID 16722)
-- Name: purchases_purchaseitem purchases_purchaseit_medicine_id_74a97fa7_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchases_purchaseitem
    ADD CONSTRAINT purchases_purchaseit_medicine_id_74a97fa7_fk_inventory FOREIGN KEY (medicine_id) REFERENCES public.inventory_medicine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5050 (class 2606 OID 16632)
-- Name: purchases_purchaseitem purchases_purchaseit_purchase_id_a7f96c61_fk_purchases; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchases_purchaseitem
    ADD CONSTRAINT purchases_purchaseit_purchase_id_a7f96c61_fk_purchases FOREIGN KEY (purchase_id) REFERENCES public.purchases_purchase(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5051 (class 2606 OID 16653)
-- Name: sales_sale sales_sale_customer_id_2d66a408_fk_customers_customer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_customer_id_2d66a408_fk_customers_customer_id FOREIGN KEY (customer_id) REFERENCES public.customers_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5052 (class 2606 OID 16658)
-- Name: sales_sale sales_sale_user_id_c0f47f66_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_user_id_c0f47f66_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5053 (class 2606 OID 17069)
-- Name: sales_saleitem sales_saleitem_medicine_id_a5bd8707_fk_inventory_medicine_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT sales_saleitem_medicine_id_a5bd8707_fk_inventory_medicine_id FOREIGN KEY (medicine_id) REFERENCES public.inventory_medicine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5054 (class 2606 OID 16671)
-- Name: sales_saleitem sales_saleitem_sale_id_56e67045_fk_sales_sale_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT sales_saleitem_sale_id_56e67045_fk_sales_sale_id FOREIGN KEY (sale_id) REFERENCES public.sales_sale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5057 (class 2606 OID 18038)
-- Name: sales_salepayment sales_salepayment_sale_id_894e0b7b_fk_sales_sale_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_salepayment
    ADD CONSTRAINT sales_salepayment_sale_id_894e0b7b_fk_sales_sale_id FOREIGN KEY (sale_id) REFERENCES public.sales_sale(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-08-20 11:39:07

--
-- PostgreSQL database dump complete
--

\unrestrict Jg1dnvEIA0Ck9lpZdxaHCJhryJ9kpZLB6gc6xymuGJsAJHGhgTLI7vEsYZOhdZI

