# Generated by Django 6.0.7 on 2026-08-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_seed_drug_interactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sensitive",
            field=models.BooleanField(
                default=False,
                help_text="Flag medicines that require staff approval at POS checkout.",
                verbose_name="sensitive medicine",
            ),
        ),
    ]
