# Generated by Django 6.0.7 on 2026-08-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_medicinegroup_product_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_a", models.CharField(max_length=255)),
                ("drug_b", models.CharField(max_length=255)),
                (
                    "interaction_level",
                    models.CharField(
                        choices=[
                            ("beneficial", "Beneficial"),
                            ("caution", "Caution"),
                            ("avoid", "Avoid"),
                            ("high_risk", "High Risk"),
                            ("contraindicated", "Contraindicated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pair_key",
                    models.CharField(
                        editable=False,
                        help_text="Normalized unordered pair used to prevent duplicate/reversed interactions.",
                        max_length=511,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "drug interaction",
                "verbose_name_plural": "drug interactions",
                "ordering": ["drug_a", "drug_b"],
            },
        ),
    ]
