# Generated by Django 6.0.7 on 2026-08-17 10:27

from django.db import migrations


def build_pair_key(drug_a, drug_b):
    return "||".join(sorted((drug_a.strip().lower(), drug_b.strip().lower())))


def seed_drug_interactions(apps, schema_editor):
    DrugInteraction = apps.get_model("inventory", "DrugInteraction")
    interactions = [
        ("Amoxicillin", "Clavulanic acid", "beneficial"),
        ("Levodopa", "Carbidopa", "beneficial"),
        ("Piperacillin", "Tazobactam", "beneficial"),
        ("Trimethoprim", "Sulfamethoxazole", "beneficial"),
        ("Amoxicillin", "Methotrexate", "caution"),
        ("Warfarin", "Ibuprofen", "avoid"),
        ("Warfarin", "Aspirin", "high_risk"),
        ("Sildenafil", "Nitroglycerin", "contraindicated"),
        ("Simvastatin", "Clarithromycin", "avoid"),
        ("Metformin", "Contrast dye", "caution"),
        ("SSRI/Sertraline", "Tramadol", "high_risk"),
        ("ACE inhibitor/Enalapril", "Spironolactone", "caution"),
        ("Tetracycline", "Calcium", "avoid"),
        ("Levothyroxine", "Calcium", "avoid"),
        ("Levothyroxine", "Iron", "avoid"),
    ]
    for drug_a, drug_b, level in interactions:
        DrugInteraction.objects.get_or_create(
            pair_key=build_pair_key(drug_a, drug_b),
            defaults={
                "drug_a": drug_a,
                "drug_b": drug_b,
                "interaction_level": level,
                "description": "",
                "is_active": True,
            },
        )


def remove_drug_interactions(apps, schema_editor):
    DrugInteraction = apps.get_model("inventory", "DrugInteraction")
    DrugInteraction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_druginteraction"),
    ]

    operations = [
        migrations.RunPython(
            seed_drug_interactions, reverse_code=remove_drug_interactions
        ),
    ]
