# Generated by Django 6.1 on 2026-08-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['medicine__name'],
            },
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='inventory_m_name_7f2fd2_idx',
            old_name='inventory_medicine_name_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='inventory_m_generic_acb93c_idx',
            old_name='inventory_medicine_generic_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='inventory_m_manufac_d4d4cb_idx',
            old_name='inventory_medicine_manuf_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='inventory_m_expiry__3d60fd_idx',
            old_name='inventory_medicine_expiry_idx',
        ),
        migrations.AddField(
            model_name='inventory',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.medicine'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['current_stock'], name='inventory_i_current_13b727_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['minimum_stock'], name='inventory_i_minimum_c2e85e_idx'),
        ),
    ]
