# Generated by Django 6.1 on 2026-08-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ("inventory", "0004_inventorytransaction"),
    ("sales", "0003_convert_saleitem_to_medicine_schema"),
    ("purchases", "0002_remove_purchaseitem_product_purchaseitem_medicine_and_more"),
]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
