# Generated by Django 6.1 on 2026-08-19 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pcs_per_strip',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strips_per_box',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
