# Generated by Django 6.1 on 2026-08-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_medicinegroup_medicine_cost_price_medicine_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expired', 'Expired'), ('near_expiry', 'Near Expiry')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type'], name='inventory_n_notific_ed75b1_idx'), models.Index(fields=['severity'], name='inventory_n_severit_8d3c0b_idx'), models.Index(fields=['is_read'], name='inventory_n_is_read_8ccea4_idx')],
            },
        ),
    ]
