# Generated by Django 6.1 on 2026-08-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_medicine_pcs_per_strip_medicine_strips_per_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='inventory.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='inventory.medicine')),
            ],
            options={
                'ordering': ['medicine_a__name', 'medicine_b__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('medicine_a', models.F('medicine_b')), _negated=True), name='different_medicines_in_interaction'), models.UniqueConstraint(fields=('medicine_a', 'medicine_b'), name='unique_drug_interaction_pair')],
            },
        ),
    ]
