# Generated by Django 6.1 on 2026-08-19 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_convert_saleitem_to_medicine_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_type',
            field=models.CharField(choices=[('PC', 'PC'), ('STRIP', 'Strip'), ('BOX', 'Box')], default='PC', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE', 'Mobile Money'), ('SPLIT', 'Split Payment')], max_length=10),
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE', 'Mobile Money')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sale', 'payment_method'), name='unique_payment_method_per_sale')],
            },
        ),
    ]
