# Generated by Django 6.1 on 2026-08-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_options_saleitem_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('SPLIT', 'Split Payment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], max_length=10),
        ),
    ]
