# Generated by Django 6.0.7 on 2026-09-05 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("requested_date", models.DateTimeField()),
                (
                    "supplier_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("status", models.CharField(default="REQUESTED", max_length=20)),
                ("confirmed_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="", null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="confirmed_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="confirmed_supplier_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        db_column="medicine_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="supplier_orders",
                        to="inventory.inventoryproduct",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        db_column="supplier_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="supplier_orders",
                        to="inventory.inventorysupplier",
                    ),
                ),
            ],
            options={
                "db_table": "supplier_supplierorder",
                "managed": True,
            },
        ),
    ]
